{% set name = "colored-traceback" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/colored-traceback-{{ version }}.tar.gz
  sha256: 6da7ce2b1da869f6bb54c927b415b95727c4bb6d9a84c4615ea77d9872911b05

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pygments
    - python >={{ python_min }}

test:
  imports:
    - colored_traceback
    - colored_traceback.always
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.github.com/staticshock/colored-traceback.py
  summary: Automatically color uncaught exception tracebacks
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
